<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class RefMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('ref_menu')->insert([
            [
                'id' => 1,
                'menu' => 'Dashboard',
                'parent_id' => 0,
                'posisi' => 1,
                'jenis_menu' => 'Backend',
                'is_active' => 1,
                'url' => 'dashboard',
                'icon' => 'ki-home-2',
                'type' => 'module',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'menu' => 'Utilitas',
                'parent_id' => 0,
                'posisi' => 5,
                'jenis_menu' => 'Backend',
                'is_active' => 1,
                'url' => '#',
                'icon' => 'ki-abstract-37',
                'type' => 'module',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'menu' => 'Daftar Modul',
                'parent_id' => 2,
                'posisi' => 1,
                'jenis_menu' => 'Backend',
                'is_active' => 1,
                'url' => 'utilitas/menu',
                'icon' => 'ki-home-2',
                'type' => 'controller',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'menu' => 'Group/ Role',
                'parent_id' => 2,
                'posisi' => 2,
                'jenis_menu' => 'Backend',
                'is_active' => 1,
                'url' => 'utilitas/role',
                'icon' => 'ki-home-2',
                'type' => 'controller',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'menu' => 'Setting Aplikasi',
                'parent_id' => 2,
                'posisi' => 3,
                'jenis_menu' => 'Backend',
                'is_active' => 1,
                'icon' => '',
                'url' => 'utilitas/setting',
                'type' => 'controller',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'menu' => 'Master Data',
                'parent_id' => 0,
                'posisi' => 4,
                'jenis_menu' => 'Backend',
                'is_active' => 1,
                'url' => '#',
                'icon' => 'ki-abstract-26',
                'type' => 'module',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'menu' => 'Data Pengguna',
                'parent_id' => 6,
                'posisi' => 1,
                'jenis_menu' => 'Backend',
                'is_active' => 1,
                'icon' => '',
                'url' => 'master/user',
                'type' => 'controller',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'menu' => 'Instansi',
                'parent_id' => 6,
                'posisi' => 2,
                'jenis_menu' => 'Backend',
                'is_active' => 1,
                'icon' => '',
                'url' => 'master/instansi',
                'type' => 'controller',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9,
                'menu'=> 'Rapat',
                'parent_id' => 0,
                'posisi' => 2,
                'jenis_menu' => 'Backend',
                'is_active' => 1,
                'url' => 'rapat/index',
                'icon' => 'ki-book-open',
                'type' => 'module',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'menu' => 'Agenda',
                'parent_id' => 9,
                'posisi' => 1,
                'jenis_menu' => 'Backend',
                'is_active' => 1,
                'icon' => '',
                'url' => 'rapat/agenda',
                'type' => 'controller',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                ],
                [
                'id' => 11,
                'menu' => 'Presensi Rapat',
                'parent_id' => 0,
                'posisi' => 3,
                'jenis_menu' => 'Backend',
                'is_active' => 1,
                'icon' => 'ki-questionnaire-tablet',
                'url' => 'rapat/presensi',
                'type' => 'controller',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                ],
                [
                'id' => 12,
                'menu' => 'Peserta',
                'parent_id' => 9,
                'posisi' => 2,
                'jenis_menu' => 'Backend',
                'is_active' => 1,
                'icon' => '',
                'url' => 'rapat/peserta',
                'type' => 'controller',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 13,
                'menu' => 'Kesimpulan',
                'parent_id' => 9,
                'posisi' => 3,
                'jenis_menu' => 'Backend',
                'is_active' => 1,
                'icon' => '',
                'url' => 'rapat/kesimpulan',
                'type' => 'controller',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Add the rest of the menu items here following the same structure
        ]);
    }
}
